### ISSUE TITLE
Не срабатывает скрипт из-за round()

### ISSUE THREAD

**Issue by tjradenot** [airens/interactive_brokers_tax#36]
на 428 строке
```
# In[12]:


div_final_tax_rest_sum = (div_tax_rest_sum + div_accurals_tax_rest_sum).round(2)
div_final_sum = (div_sum + div_accurals_sum).round(2)
div_tax_paid_final_sum = (div_tax_paid_rub_sum + div_accurals_tax_paid_rub_sum).round(2)
div_tax_need_pay_final_sum = (div_tax_rest_sum + div_accurals_tax_rest_sum).round(2)
```
вот так сработало:

```
div_final_tax_rest_sum = round((div_tax_rest_sum + div_accurals_tax_rest_sum), 2)
div_final_sum = round((div_sum + div_accurals_sum), 2)
div_tax_paid_final_sum = round((div_tax_paid_rub_sum + div_accurals_tax_paid_rub_sum), 2)
div_tax_need_pay_final_sum = round((div_tax_rest_sum + div_accurals_tax_rest_sum), 2)

```

**Comment by airens** [comment]
у всех всё срабатывает, а у вас нет?

**Comment by tjradenot** [comment]
> у всех всё срабатывает, а у вас нет?

Вот такую ошибку выдает:

```
Traceback (most recent call last):
  File "ib.py", line 428, in <module>
    div_final_tax_rest_sum = (div_tax_rest_sum + div_accurals_tax_rest_sum).round(2)
AttributeError: 'int' object has no attribute 'round'

```

**Comment by Intar** [comment]
Скорее всего вы передаете не тот отчет, такая ошибка будет, если не получилось получить данные из отчета.
Нужно брать годовой отчет, а не налоговый по дивидендам.
Reports->Statements->Activity->Period=Annual, Format=csv
И он должен быть на английском, если у вас личным кабинет на русском, то переключите на английский перед формированием отчета.

**Comment by tjradenot** [comment]
Спасибо. Попробую.

**Comment by revic50** [comment]
Та же ошибка:

```
AttributeError: 'float' object has no attribute 'rint'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\interactive_brokers_tax-master\ib.py", line 383, in <module>
    div_res = div_calc()
              ^^^^^^^^^^
  File "D:\interactive_brokers_tax-master\ib.py", line 374, in div_calc
    res["tax_paid"] = -div_tax["amount"].values.round(2) if div_tax is not None else 0
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: loop of ufunc does not support argument 0 of type float which has no callable rint method
```
Отчеты на английском. Ошибка возникает только за 2020 год, 2021, 2022 и 2023 без ошибок.

**Comment by revic50** [comment]
Та же ошибка:

```
Traceback (most recent call last):
  File "D:\interactive_brokers_tax-master\ib.py", line 625, in <module>
    create_doc()
  File "D:\interactive_brokers_tax-master\ib.py", line 621, in create_doc
    'deduction_total_sum': (fees_rub_sum + deduction_sum).round(2)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'round'
```

Только за 2020 год (самый первый отчет), остальные отрабатывает без ошибок.
